
filebeat.inputs:
- input_type: log
  paths:
    - /var/log/suricata/eve.json
  json.keys_under_root: true
  json.overwrite_keys: false
  json.add_error_key: true
output.elasticsearch: 
  hosts: ["https://url:9243"]
  username: "elastic"
  password: "psw"
  index: "suricata-%{+yyyy.MM.dd}"
setup.template.name: "suricata"
setup.template.pattern: "suricata-*"
setup.ilm.enabled: false
